// react/calculadora/src/main/Calculator.jsx
import React, { Component } from 'react'
import './Calculator.css'

import Button from '../componets/Button'
import Display from '../componets/Display'

const initialState = {
    displayValue: '0',
    clearDisplay: false,
    operation: null,
    values: [0, 0],
    current: 0
}

export default class Calculator extends Component {

    state = { ...initialState}

    constructor(props) {
        super(props)
        this.clearMemory = this.clearMemory.bind(this)
        this.setOperation = this.setOperation.bind(this)
        this.addDigit = this.addDigit.bind(this)
    }

    clearMemory(){
        this.setState({ ...initialState })
    }

    setOperation(operation) {
        console.log(operation)
    }

    addDigit(n) {
        if (n === '.' && this.state.displayValue.includes('.')) {
            return
        }

        const clearDisplay = this.state.displayValue === '0'
            || this.state.clearDisplay
            const currentValue = clearDisplay ? '' : this.state.displayValue
            const displayValue = currentValue + n
            this.setState({ displayValue, clearDisplay: false })

            if (n !== '.') {
                const i = this.state.current
                const newValue = parseFloat(displayValue)
                const values = [...this.state.values]
                values[i] = newValue
                this.setState({ values })
                console.log(values)
            }
    }
    render() {        
        return (
            <div className="calculator">
                <Display value={this.state.displayValue} />
                <Button label="AC" click={this.clearMemory} triple/>
                <Button label="/" click={this.setOperation} operation/>
                <Button label="7" click={this.addDigit} />
                <Button label="8" click={this.addDigit} />
                <Button label="9" click={this.addDigit} />
                <Button label="*" click={this.setOperation} operation/>
                <Button label="4" click={this.addDigit} />
                <Button label="5" click={this.addDigit} />
                <Button label="6" click={this.addDigit} />
                <Button label="-" click={this.setOperation} operation/>
                <Button label="1" click={this.addDigit} />
                <Button label="2" click={this.addDigit} />
                <Button label="3" click={this.addDigit} />
                <Button label="+" click={this.setOperation} operation/>
                <Button label="0" click={this.addDigit} double/>
                <Button label="." click={this.addDigit} />
                <Button label="=" click={this.setOperation} 
                />              
                
            </div>
        )
    }
}

// vue/calculator/src/main/Calculator.vue
<template>
  <div class="calculator">
      <Display value="10000" />
      <Button label="AC" triple @meuOnClick="clearMemory" />      
      <Button label="/" operation @meuOnClick="setOperation" />      
      <Button label="7" @meuOnClick="addDigit" />      
      <Button label="8" @meuOnClick="addDigit" />      
      <Button label="9" @meuOnClick="addDigit" />      
      <Button label="*" operation @meuOnClick="setOperation" />      
      <Button label="4" @meuOnClick="addDigit" />      
      <Button label="5" @meuOnClick="addDigit" />      
      <Button label="6" @meuOnClick="addDigit" />      
      <Button label="-" operation @meuOnClick="setOperation" />      
      <Button label="1" @meuOnClick="addDigit" />      
      <Button label="2" @meuOnClick="addDigit" />      
      <Button label="3" @meuOnClick="addDigit" />      
      <Button label="+" operation @meuOnClick="setOperation" />      
      <Button label="0" double @meuOnClick="addDigit" />      
      <Button label="." @meuOnClick="addDigit" />      
      <Button label="=" operation @meuOnClick="setOperation" />    
         
    </div>
</template>

<script>
import Button from "../components/Button"
import Display from "../components/Display"

export default {
    components: { Button, Display},
    methods: {
        clearMemory() {
            console.log('Limpar Memória!')
        },
        setOperation(operation) {
            console.log('Operação ' + operation)
        },
        addDigit(n) {
            console.log('Digito ' + n)
        }
    }

}
</script>

<style>
.calculator {
    height: 321px;
    width: 235px;
    border-radius: 5px;
    overflow: hidden;

    display: grid;
    grid-template-columns: repeat(4, 25%) ;
    grid-template-rows: 1fr 48px 48px 48px 48px 48px;
}
</style>
